# Generated by Django 4.0 on 2021-12-12 06:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pujas',
            name='puja_pic',
            field=models.ImageField(default=datetime.datetime(2021, 12, 12, 6, 47, 49, 72214, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
    ]
