# Generated by Django 4.0 on 2021-12-12 08:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_pujas_puja_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='pujas',
            name='category',
            field=models.CharField(default=datetime.datetime(2021, 12, 12, 8, 14, 24, 108699, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
