# Generated by Django 4.0 on 2021-12-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_pujas_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pujas',
            name='puja_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
