# Generated by Django 4.0 on 2021-12-12 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_news_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='event_pic',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='pujas',
            old_name='puja_pic',
            new_name='image',
        ),
    ]
